version: '3.8'

services:
  db:
    image: postgres:15
    container_name: azimut_postgres
    environment:
      POSTGRES_USER: xxxx
      POSTGRES_PASSWORD: xxxxx
      POSTGRES_DB: azimut_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build:
      context: ./AzimutServer
    container_name: azimut_api
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      DB_USER: xxxx
      DB_PWD: xxxx
      DB_NAME: azimut_db
      DB_HOST: db
    volumes:
      - ./AzimutServer:/app

volumes:
  pgdata:
