name: Run API & Client Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  api-tests:
    name: Run API Tests (Pytest)
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: azimut_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python dependencies
        working-directory: ./AzimutServer
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Wait for PostgreSQL to be ready
        run: |
          until pg_isready -h localhost -p 5432; do
            echo "Waiting for postgres..."
            sleep 2
          done
      - name: Run API tests
        working-directory: ./AzimutServer
        env:
          DB_USER: postgres
          DB_PWD: postgres
          DB_NAME: azimut_db
          DB_HOST : localhost
        run: pytest tests/test_targets.py

  client-tests:
    name: Run React Component Tests
    env:
      CI: true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install NPM dependencies
        working-directory: ./azimut_client
        run: npm install

      - name: Run React tests
        working-directory: ./azimut_client
        run: npm test -- --watchAll=false src/__tests__/TargetTable.test.tsx src/__tests__/ThreatBadge.test.tsx